Improve `run` error handling and tests.

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -14225,9 +14225,13 @@ _run() {
   local _notebook_path
   _notebook_path="$(_notebooks current --path)"
 
-  cd "${_notebook_path}"  || _exit_1 printf "_run() \`cd\` failed.\\n"
-  [[ -n "${*}" ]]         || _exit_1 printf "Command required.\\n"
-  type "${1}" >/dev/null 2>&1 || _exit_1 printf "Command \`${1}\` not available.\\n"
+  cd "${_notebook_path}"    || _exit_1 printf "_run() \`cd\` failed.\\n"
+  [[ -n "${*}" ]]           || _exit_1 printf "Command required.\\n"
+
+  if ! _command_exists "${1:-}"
+  then
+    _exit_1 printf "Command not found: %s\\n" "$(_color_primary "${1:-}")"
+  fi
 
   ("${@}")
 }
