Filter todos with `--tag <tag>` option.
refs gh-294

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -4415,12 +4415,12 @@ $(_color_primary "Usage"):
   ${_ME} todo add [<notebook>:][<folder-path>/][<filename>] <title>
               [--description <description>] [--due <date>]
               [-r (<url> | <selector>) | --related (<url> | <selector>)]
-              [--tags <tag1>,<tag2>...] [--task <title>]...
+              [--tags <tag1>,<tag2>...] [--task <title>...]
   ${_ME} todo do   ([<notebook>:][<folder-path>/][<id> | <filename> | <description>])
                [<task-number>]
   ${_ME} todo undo ([<notebook>:][<folder-path>/][<id> | <filename> | <description>])
                [<task-number>]
-  ${_ME} todos [<notebook>:][<folder-path>/] [open | closed]
+  ${_ME} todos [<notebook>:][<folder-path>/] [open | closed] [--tags <tag1>,<tag2>...]
   ${_ME} todos tasks ([<notebook>:][<folder-path>/][<id> | <filename> | <description>])
                  [open | closed]
   ${_ME} unarchive [<notebook>]
@@ -17522,6 +17522,9 @@ _search() {
                 [[ "${_type}" =~ (^bookmark$|^bookmarks$)                   ]] &&
                   _file_is_bookmark "${_path}"
                 } || {
+                  [[ "${_type}" =~ (^todo$|^todos$|^task$|^tasks$)          ]] &&
+                  _file_is_todo "${_path}"
+                } || {
                   [[ "${_type}" =~ (^note$|^notes$|^text$)                  ]] &&
                   _file_is_text "${_path}"
                 } || {
@@ -17863,9 +17866,9 @@ _search() {
         then
           return 0
         else
-          printf "Not found in %s: %s\\n"               \
-            "$(_color_primary "${_search_selector:-}")" \
-            "$(_color_primary "${_query_message:-}")"
+          _warn printf "Not found in %s: %s\\n"               \
+                  "$(_color_primary "${_search_selector:-}")" \
+                  "$(_color_primary "${_query_message:-}")"
         fi
       fi
 
@@ -25198,12 +25201,12 @@ $(_color_primary "Usage"):
   ${_ME} todo add [<notebook>:][<folder-path>/][<filename>] <title>
               [--description <description>] [--due <date>]
               [-r (<url> | <selector>) | --related (<url> | <selector>)]
-              [--tags <tag1>,<tag2>...] [--task <title>]...
+              [--tags <tag1>,<tag2>...] [--task <title>...]
   ${_ME} todo do   ([<notebook>:][<folder-path>/][<id> | <filename> | <description>])
                [<task-number>]
   ${_ME} todo undo ([<notebook>:][<folder-path>/][<id> | <filename> | <description>])
                [<task-number>]
-  ${_ME} todos [<notebook>:][<folder-path>/] [open | closed]
+  ${_ME} todos [<notebook>:][<folder-path>/] [open | closed] [--tags <tag1>,<tag2>...]
   ${_ME} todos tasks ([<notebook>:][<folder-path>/][<id> | <filename> | <description>])
                  [open | closed]
 
@@ -25342,7 +25345,9 @@ _todo() {
   local _only_todos=0
   local _option_title=
   local _related_identifiers=()
-  local _tag_list=
+  local _tag_list_with_commas=
+  local _tag_list_with_spaces=
+  local _tags=()
   local _task_list_options=()
   local _tasks=()
 
@@ -25368,8 +25373,14 @@ _todo() {
         shift
         ;;
       --tag*)
-        [[ -n "${_tag_list:-}"  ]] && _tag_list+=" "
-        _tag_list+="$(_option_get_tags "${1}" "${2:-}")"
+        [[ -n "${_tag_list_with_commas:-}"  ]] && _tag_list_with_commas+=","
+        _tag_list_with_commas+="$(_option_get_tags "${1}" "${2:-}")"
+
+        [[ -n "${_tag_list_with_spaces:-}"  ]] && _tag_list_with_spaces+=" "
+
+        _tag_list_with_spaces+="$(_option_get_tags "${1}" "${2:-}")"
+
+        _tags+=("${2:-}")
 
         shift
         ;;
@@ -25538,15 +25549,15 @@ _todo() {
         _todo_content+="${_NEWLINE}"
       fi
 
-      if [[ -n "${_tag_list:-}"         ]]
+      if [[ -n "${_tag_list_with_spaces:-}" ]]
       then
         _todo_content+="${_NEWLINE}## Tags${_NEWLINE}"
-        _todo_content+="${_NEWLINE}${_tag_list}${_NEWLINE}"
+        _todo_content+="${_NEWLINE}${_tag_list_with_spaces}${_NEWLINE}"
       fi
 
-      _add                              \
-        --content "${_todo_content:-}"  \
-        --type    "todo.md"             \
+      _add                                  \
+        --content "${_todo_content:-}"      \
+        --type    "todo.md"                 \
         "${_arguments[@]:-}"
       ;;
     do|undo)
@@ -25660,7 +25671,20 @@ _todo() {
       ;;
     list)
       {
-        _list "${_arguments[@]:-}" --error-on-empty --type todo 2>/dev/null
+        if [[ -n "${_tag_list_with_commas:-}"   ]]
+        then
+          _search                               \
+            "${_arguments[@]:-}"                \
+            --tags "${_tag_list_with_commas:-}" \
+            --type todo                         \
+            --list 2>/dev/null
+        else
+          _list                   \
+            "${_arguments[@]:-}"  \
+            --error-on-empty      \
+            --type todo           \
+            2>/dev/null
+        fi
       } | {
         case "${_filter:-}" in
           closed)
@@ -25757,14 +25781,25 @@ _todo() {
       )
 
       {
-        _list "${_selector_path:-}"     \
-          --error-on-empty              \
-          --no-id                       \
-          --no-indicator                \
-          --path                        \
-          --type md                     \
-          "${_task_list_options[@]:-}"  \
-          2>/dev/null || printf ""
+        if [[ -n "${_tag_list_with_commas:-}"   ]]
+        then
+          _search                               \
+            "${_selector_path:-}"               \
+            "${_task_list_options[@]:-}"        \
+            --tags "${_tag_list_with_commas:-}" \
+            --type todo                         \
+            --path
+        else
+          _list "${_selector_path:-}"     \
+            --error-on-empty              \
+            --no-id                       \
+            --no-indicator                \
+            --path                        \
+            --type md                     \
+            "${_task_list_options[@]:-}"  \
+            2>/dev/null || printf ""
+        fi
+
       } | {
         local _first=1
         local _in_task_list_item=0
