Use `age` password prompt during decryption.
refs gh-156

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -8853,11 +8853,6 @@ _decrypt_file() {
   local _encrypted_path="${1:-}"
   local _password="${2:-}"
 
-  if [[ -z "${_password}"       ]]
-  then
-    _exit_1 printf "Password required.\\n"
-  fi
-
   if [[ -z "${_encrypted_path}" ]]
   then
     return 1
@@ -8872,23 +8867,7 @@ _decrypt_file() {
   _file_command_response="$(file "${_encrypted_path}" 2>/dev/null || :)"
 
   local _decryption_tool=
-
-  if [[   "${_file_command_response}" =~ data     ]]
-  then
-    local         __first_line=
-    IFS=  read -r __first_line < "${_encrypted_path}"
-
-    if [[ "${__first_line:-}" =~ age-encryption   ]]
-    then
-      _decryption_tool="age"
-    fi
-  elif [[ "${_file_command_response}" =~ GPG|PGP  ]]
-  then
-    _decryption_tool="gpg"
-  elif [[ "${_file_command_response}" =~ openssl  ]]
-  then
-    _decryption_tool="openssl"
-  fi
+  _decryption_tool="$(_get_decryption_tool "${_encrypted_path:-}")"
 
   case "${_decryption_tool:-}" in
     age)
@@ -9186,6 +9165,41 @@ _encrypt_file() {
   then
     _exit_1 printf "Encryption error.\\n"
   fi
+}
+
+# _get_decryption_tool()
+#
+# Usage:
+#   _get_decryption_tool <path>
+#
+# Description:
+#   Print the name of the tool to use to decrypt the file at <path>.
+_get_decryption_tool() {
+  local _encrypted_path="${1:-}"
+
+  local _file_command_response=
+  _file_command_response="$(file "${_encrypted_path}" 2>/dev/null || :)"
+
+  local _decryption_tool=
+
+  if [[   "${_file_command_response}" =~ GPG|PGP  ]]
+  then
+    _decryption_tool="gpg"
+  elif [[ "${_file_command_response}" =~ openssl  ]]
+  then
+    _decryption_tool="openssl"
+  elif [[ "${_file_command_response}" =~ data     ]]
+  then
+    local         __first_line=
+    IFS=  read -r __first_line < "${_encrypted_path}"
+
+    if [[ "${__first_line:-}" =~ age-encryption   ]]
+    then
+      _decryption_tool="age"
+    fi
+  fi
+
+  printf "%s\\n" "${_decryption_tool:-}"
 }
 
 # _get_hash()
@@ -12932,17 +12946,26 @@ _edit() {
     then
       _encrypted_path="${_target_file}"
 
-      if [[ -z "${_password}"     ]]
+      local _decryption_tool=
+      _decryption_tool="$(_get_decryption_tool "${_encrypted_path:-}")"
+
+      if [[    "${_decryption_tool:-}" != "age"   ]] &&
+         [[ -z "${_password}"                     ]]
       then
         # request password without displaying it
         printf "%s: " "$(_color_primary "Password")"
 
-        local _password=
         IFS='' read -r -e -d $'\n' -s _password </dev/tty
+
         printf "\\n" # print newline to stop `read`
+
+        if [[ -z "${_password}"                   ]]
+        then
+          _exit_1 printf "Password required.\\n"
+        fi
       fi
 
-      _decrypted_path="$(_decrypt_file "${_target_file}" "${_password}")"
+      _decrypted_path="$(_decrypt_file "${_target_file}" "${_password:-}")"
 
       _target_file="${_decrypted_path}"
 
@@ -16357,7 +16380,11 @@ ${_title/\[$' '\]/${_TPUT_SETAF_8}[ ]${_TPUT_SGR0}}"
     local _encrypted_path=
     _encrypted_path="${_target_path}"
 
-    if [[ -z "${_password}" ]]
+    local _decryption_tool=
+    _decryption_tool="$(_get_decryption_tool "${_encrypted_path:-}")"
+
+    if [[    "${_decryption_tool:-}" != "age" ]] &&
+       [[ -z "${_password}"                   ]]
     then
       # request password without displaying it
       printf "%s: " "$(_color_primary "Password")"
@@ -16365,11 +16392,11 @@ ${_title/\[$' '\]/${_TPUT_SETAF_8}[ ]${_TPUT_SGR0}}"
       local _password=
       IFS='' read -r -e -d $'\n' -s _password </dev/tty
       printf "\\n" # print newline to stop `read`
-    fi
 
-    if [[ -z "${_password}" ]]
-    then
-      _exit_1 printf "Password required.\\n"
+      if [[ -z "${_password}"                 ]]
+      then
+        _exit_1 printf "Password required.\\n"
+      fi
     fi
 
     local _decrypted_path=
@@ -19681,6 +19708,9 @@ _helpers() {
       ;;
     decrypt*)
       _decrypt_file                   "${_options[@]:-}"
+      ;;
+    *decryption*)
+      _get_decryption_tool            "${_options[@]:-}"
       ;;
     download*)
       _download_from                  "${_options[@]:-}"
