Improve input and error handling in `ls`.

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -5775,35 +5775,29 @@ _ls() {
     _use_pager=1
   fi
 
-  if ((_use_pager)) && [[ -n "${PAGER:-}" ]] && [[ ! "${PAGER}" =~ less ]]
-  then
-    "${PAGER}"
-  elif ((_use_pager)) && _command_exists "less"
-  then
-    less -r --CLEAR-SCREEN --prompt="$(_less_prompt)"
-  else
-    cat
-  fi < <({
+  {
     printf "%s" "${_maybe_notebook_list}"
 
     _list -n "${_limit}" "${_args[@]:-}" 2>/dev/null ||
       {
         if [[ -n "${_args[*]:-}" ]]
         then
+          local _maybe_name="${_args[0]:-}"
+          _maybe_name="$(printf "%s\\n" "${_maybe_name}" | sed 's/\:$//')"
+
           local _notebook=
-          _notebook="$(_notebooks list "${_args[0]:-}" 2>/dev/null)" || :
+          _notebook="$(_notebooks list "${_maybe_name:-}" 2>/dev/null)" || :
         fi
 
         if [[ -n "${_notebook:-}" ]]
         then
-          _NOTEBOOK_PATH="${NB_DIR}/${_notebook}"
-          _SCOPE="${_notebook}"
-          _SCOPED=1
-          _ls
+          _NOTEBOOK_PATH="${NB_DIR}/${_notebook}" \
+            _SCOPE="${_notebook}"                 \
+            _SCOPED=1                             \
+            _ls
           return 0
         else
-          _exit_1 printf "Not found: %s\\n" \
-            "$(_highlight "${_args[0]:-}")"
+          _exit_1 printf "Not found: %s\\n" "$(_highlight "${_args[0]:-}")"
         fi
       }
 
@@ -5901,7 +5895,15 @@ _ls() {
 ${_output_hi}
 HEREDOC
     fi
-  })
+  } | if ((_use_pager)) && [[ -n "${PAGER:-}" ]] && [[ ! "${PAGER}" =~ less ]]
+      then
+        "${PAGER}"
+      elif ((_use_pager)) && _command_exists "less"
+      then
+        less -r --CLEAR-SCREEN --prompt="$(_less_prompt)"
+      else
+        cat
+      fi
 }
 
 # move ################################################################### move
