Move conditional error output to where `_browse_serve()` is called.

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -22717,10 +22717,6 @@ HEREDOC
     case "${NB_BROWSE_SERVER_TOOL:-}" in
       ncat)
         (
-          if ! ((${_USE_DEBUG:-0}))
-          then
-            exec 2>/dev/null
-          fi
 
           ncat                                      \
             --exec "${_MY_PATH} browse --respond"   \
@@ -22732,11 +22728,6 @@ HEREDOC
       nc|netcat)
         # TODO: improve concurrency
         (
-          if ! ((${_USE_DEBUG:-0}))
-          then
-            exec 2>/dev/null
-          fi
-
           while true
           do
             nc                                      \
@@ -22749,11 +22740,6 @@ HEREDOC
         ;;
       socat)
         (
-          if ! ((${_USE_DEBUG:-0}))
-          then
-            exec 2>/dev/null
-          fi
-
           socat                                                                               \
             tcp-listen:"${NB_SERVER_PORT}",bind="${NB_SERVER_HOST:-localhost}",reuseaddr,fork \
             "system:{ ${_MY_PATH} browse --respond; }"
@@ -23254,7 +23240,12 @@ HEREDOC
 
   # start server
 
-  _browse_serve || : # TODO: return status
+  if ! ((${_USE_DEBUG:-0}))
+  then
+    _browse_serve 2>/dev/null || : # TODO: return status
+  else
+    _browse_serve             || : # TODO: return status
+  fi
 
   # request URL
 
