Add `-p` / `--pager` option to `list`.

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -5265,6 +5265,7 @@ _list() {
   local _selection
   local _sort=0
   local _type=
+  local _use_pager=0
 
   _debug printf "_list() \${@:-}: '%s'\\n" "${@:-}"
 
@@ -5303,6 +5304,9 @@ _list() {
           _limit="${__val:-}"
           shift
         fi
+        ;;
+      -p|--pager|--less)
+        _use_pager=1
         ;;
       -s|--sort)
         _sort=1
@@ -5375,10 +5379,11 @@ _list() {
     "list() \${_filenames_count}: '%s'\\n" \
     "${_filenames_count[@]}"
 
-  if [[ "${_filenames_count}" -eq 0           ]] &&
-     [[ "${_type}" =~ ^bookmark$|^bookmarks$  ]]
-  then
-    cat <<HEREDOC
+  {
+    if [[ "${_filenames_count}" -eq 0           ]] &&
+       [[ "${_type}" =~ ^bookmark$|^bookmarks$  ]]
+    then
+      cat <<HEREDOC
 0 bookmarks.
 
 Add a bookmark:
@@ -5386,10 +5391,10 @@ Add a bookmark:
 Help information:
   $(_highlight "${_ME} help bookmark")
 HEREDOC
-  elif [[ "${_filenames_count}" -eq 0 ]] &&
-       [[ "${_type}" =~ ^archive$|^audio$|^document$|^image$|^video$ ]]
-  then
-    cat <<HEREDOC
+    elif [[ "${_filenames_count}" -eq 0 ]] &&
+         [[ "${_type}" =~ ^archive$|^audio$|^document$|^image$|^video$ ]]
+    then
+      cat <<HEREDOC
 0 ${_type} files.
 
 Import a file:
@@ -5397,9 +5402,9 @@ Import a file:
 Help information:
   $(_highlight "${_ME} help import")
 HEREDOC
-  elif [[ "${_filenames_count}" -eq 0 ]]
-  then # no files in `$_NOTEBOOK_PATH`
-    cat <<HEREDOC
+    elif [[ "${_filenames_count}" -eq 0 ]]
+    then # no files in `$_NOTEBOOK_PATH`
+      cat <<HEREDOC
 0 notes.
 
 Add a note:
@@ -5411,286 +5416,296 @@ Import a file:
 Help information:
   $(_highlight "${_ME} help")
 HEREDOC
-    return 0
-  else
-    local _counter=0
-    local _max_id
-    _max_id="$(_index get_max_id)"
+      return 0
+    else
+      local _counter=0
+      local _max_id
+      _max_id="$(_index get_max_id)"
 
-    for __basename in "${_filenames[@]}"
-    do
-      _debug printf "list() \${__basename}: '%s'\\n" "${__basename}"
+      for __basename in "${_filenames[@]}"
+      do
+        _debug printf "list() \${__basename}: '%s'\\n" "${__basename}"
 
-      local _maybe_title=
+        local _maybe_title=
 
-      if [[ -n "${_selection:-}" ]]
-      then
-        # If a valid <selection> has been specified, skip the rest of the loop
-        # unless the <selection> basename matches the current one.
-        if [[ -n "${_selection_basename}" ]]
+        if [[ -n "${_selection:-}" ]]
         then
-          if [[ "${__basename}" != "${_selection_basename}" ]]
+          # If a valid <selection> has been specified, skip the rest of the loop
+          # unless the <selection> basename matches the current one.
+          if [[ -n "${_selection_basename}" ]]
           then
-            continue
-          fi
-        else
-
-          # Turn on a case-insensitive matching (-s set nocasematch)
-          shopt -s nocasematch
-
-          if [[ "${__basename:-}" =~ ${_selection} ]]
-          then
-            : # include the note in the list
+            if [[ "${__basename}" != "${_selection_basename}" ]]
+            then
+              continue
+            fi
           else
-            _maybe_title="$(_get_title "${_NOTEBOOK_PATH}/${__basename}")"
-            if [[ "${_maybe_title:-}" =~ ${_selection} ]]
+
+            # Turn on a case-insensitive matching (-s set nocasematch)
+            shopt -s nocasematch
+
+            if [[ "${__basename:-}" =~ ${_selection} ]]
             then
               : # include the note in the list
             else
-              continue # don't include note in list
+              _maybe_title="$(_get_title "${_NOTEBOOK_PATH}/${__basename}")"
+              if [[ "${_maybe_title:-}" =~ ${_selection} ]]
+              then
+                : # include the note in the list
+              else
+                continue # don't include note in list
+              fi
             fi
+
+            # Turn off a case-insensitive matching (-u unset nocasematch)
+            shopt -u nocasematch
+          fi
+        fi
+
+        if [[ -n "${_limit:-}" ]] && [[ "${_counter}" -eq "${_limit}" ]]
+        then # the limit has been reached.
+
+          _debug printf "list() \${#_limit}: '%s'\\n" "${#_limit}"
+          _debug printf "list() \${#_counter}: '%s'\\n" "${#_counter}"
+
+          local _difference
+          _difference=$((_filenames_count-_counter))
+          printf "%s omitted. %s total.\\n" \
+            "${_difference}" \
+            "${_filenames_count}"
+          break
+        fi
+
+        local _title_or_basename="${__basename}"
+        if ! ((_list_filenames))
+        then
+          if [[ -z "${_maybe_title}" ]]
+          then
+            _maybe_title="$(_get_title "${_NOTEBOOK_PATH}/${__basename}")"
           fi
 
-          # Turn off a case-insensitive matching (-u unset nocasematch)
-          shopt -u nocasematch
+          if [[ -n "${_maybe_title}" ]]
+          then # note file has title.
+            _title_or_basename="${_maybe_title}"
+          fi
         fi
-      fi
 
-      if [[ -n "${_limit:-}" ]] && [[ "${_counter}" -eq "${_limit}" ]]
-      then # the limit has been reached.
+        local _extra_length=0
+        local _indicators=
+        local _maybe_padded_indicators=
 
-        _debug printf "list() \${#_limit}: '%s'\\n" "${#_limit}"
-        _debug printf "list() \${#_counter}: '%s'\\n" "${#_counter}"
-
-        local _difference
-        _difference=$((_filenames_count-_counter))
-        printf "%s omitted. %s total.\\n" \
-          "${_difference}" \
-          "${_filenames_count}"
-        break
-      fi
-
-      local _title_or_basename="${__basename}"
-      if ! ((_list_filenames))
-      then
-        if [[ -z "${_maybe_title}" ]]
+        if ((_print_indicators))
         then
-          _maybe_title="$(_get_title "${_NOTEBOOK_PATH}/${__basename}")"
+          if _file_is_bookmark "${_NOTEBOOK_PATH}/${__basename}"
+          then
+            _indicators+="🔖 "
+          fi
+
+          if _file_is_image "${_NOTEBOOK_PATH}/${__basename}"
+          then
+            _indicators+="🌄 "
+          fi
+
+          if _file_is_document "${_NOTEBOOK_PATH}/${__basename}"
+          then
+            _indicators+="📄 "
+          fi
+
+          if [[ -d "${_NOTEBOOK_PATH}/${__basename}" ]]
+          then
+            _indicators+="📂 "
+          fi
+
+          if _file_is_video "${_NOTEBOOK_PATH}/${__basename}"
+          then
+            _indicators+="📹 "
+          fi
+
+          if _file_is_audio "${_NOTEBOOK_PATH}/${__basename}"
+          then
+            _indicators+="🔉 "
+          fi
+
+          if _file_is_encrypted "${_NOTEBOOK_PATH}/${__basename}"
+          then
+            _indicators+="🔒 "
+          fi
+
+          if [[ "${_title_or_basename}" =~ todo|Todo|TODO ]]
+          then
+            _indicators+="✅ "
+            _extra_length=1
+          fi
+
+          if [[ -n "${_indicators:-}" ]]
+          then
+            _maybe_padded_indicators="${_indicators}"
+          fi
         fi
 
-        if [[ -n "${_maybe_title}" ]]
-        then # note file has title.
-          _title_or_basename="${_maybe_title}"
-        fi
-      fi
+        local _list_item="${_maybe_padded_indicators}${_title_or_basename}"
 
-      local _extra_length=0
-      local _indicators=
-      local _maybe_padded_indicators=
-
-      if ((_print_indicators))
-      then
-        if _file_is_bookmark "${_NOTEBOOK_PATH}/${__basename}"
+        if ! ((_no_id))
         then
-          _indicators+="🔖 "
+          # NOTE: Plain version serves as the reference version and can be used
+          # for length calculations.
+          local _item_identifier=
+          local _max_identifier=
+          _item_identifier="$(_index get_id "${__basename}")"
+          if ((_SCOPED))
+          then
+            _item_identifier="${_notebook_identifier}:${_item_identifier}"
+            _max_identifier="${_notebook_identifier}:${_max_id}"
+          else
+            _item_identifier="${_item_identifier}"
+            _max_identifier="${_max_id}"
+          fi
+
+          local _id_item=
+          _id_item="[${_item_identifier}]"
+
+          local _id_item_color=
+          _id_item_color="$(_id_brackets_color "${_item_identifier}")"
+
+          # Use calculated number of spaces for nicer formatting.
+          local _spaces=''
+          local _spaces_length=1
+          _spaces_length=$(( ${#_max_identifier} + 3 - ${#_id_item} ))
+          printf -v _spaces '%*s' "${_spaces_length}"
         fi
 
-        if _file_is_image "${_NOTEBOOK_PATH}/${__basename}"
+        if ! ((_list_filenames)) &&
+           ! ((_print_excerpt))  &&
+           [[ "${_title_or_basename}" == "${__basename}" ]]
         then
-          _indicators+="🌄 "
+          local _first_line=
+          _first_line="$(_get_first_line "${_NOTEBOOK_PATH}/${__basename}")"
+
+          if [[ -n "${_first_line:-}" ]]
+          then
+            _list_item="${_list_item} · \"${_first_line}\""
+          fi
         fi
 
-        if _file_is_document "${_NOTEBOOK_PATH}/${__basename}"
-        then
-          _indicators+="📄 "
-        fi
+        local _print_item=
+        local _print_item_color=
 
-        if [[ -d "${_NOTEBOOK_PATH}/${__basename}" ]]
+        if ((_no_id))
         then
-          _indicators+="📂 "
-        fi
-
-        if _file_is_video "${_NOTEBOOK_PATH}/${__basename}"
-        then
-          _indicators+="📹 "
-        fi
-
-        if _file_is_audio "${_NOTEBOOK_PATH}/${__basename}"
-        then
-          _indicators+="🔉 "
-        fi
-
-        if _file_is_encrypted "${_NOTEBOOK_PATH}/${__basename}"
-        then
-          _indicators+="🔒 "
-        fi
-
-        if [[ "${_title_or_basename}" =~ todo|Todo|TODO ]]
-        then
-          _indicators+="✅ "
-          _extra_length=1
-        fi
-
-        if [[ -n "${_indicators:-}" ]]
-        then
-          _maybe_padded_indicators="${_indicators}"
-        fi
-      fi
-
-      local _list_item="${_maybe_padded_indicators}${_title_or_basename}"
-
-      if ! ((_no_id))
-      then
-        # NOTE: Plain version serves as the reference version and can be used
-        # for length calculations.
-        local _item_identifier=
-        local _max_identifier=
-        _item_identifier="$(_index get_id "${__basename}")"
-        if ((_SCOPED))
-        then
-          _item_identifier="${_notebook_identifier}:${_item_identifier}"
-          _max_identifier="${_notebook_identifier}:${_max_id}"
+          _print_item="${_list_item}"
+          _print_item_color="${_list_item}"
         else
-          _item_identifier="${_item_identifier}"
-          _max_identifier="${_max_id}"
+          local _list_item_id="${_id_item}${_spaces}${_list_item}"
+          local _list_item_id_color="${_id_item_color}${_spaces}${_list_item}"
+
+          _print_item="${_list_item_id}"
+          _print_item_color="${_list_item_id_color}"
         fi
 
-        local _id_item=
-        _id_item="[${_item_identifier}]"
-
-        local _id_item_color=
-        _id_item_color="$(_id_brackets_color "${_item_identifier}")"
-
-        # Use calculated number of spaces for nicer formatting.
-        local _spaces=''
-        local _spaces_length=1
-        _spaces_length=$(( ${#_max_identifier} + 3 - ${#_id_item} ))
-        printf -v _spaces '%*s' "${_spaces_length}"
-      fi
-
-      if ! ((_list_filenames)) &&
-         ! ((_print_excerpt))  &&
-         [[ "${_title_or_basename}" == "${__basename}" ]]
-      then
-        local _first_line=
-        _first_line="$(_get_first_line "${_NOTEBOOK_PATH}/${__basename}")"
-
-        if [[ -n "${_first_line:-}" ]]
+        if ((_list_color_enabled))  &&
+           ! ((_list_filenames))    &&
+           ! ((_no_id))
         then
-          _list_item="${_list_item} · \"${_first_line}\""
+          # Calculate apparent length of the list item string, with byte and
+          # character calculations for handling unicode characters.
+          #
+          # More info: https://stackoverflow.com/a/31009961
+          local _item_line_length_chars=
+          _item_line_length_chars="${#_print_item}"
+
+          LANG=C LC_ALL=C
+
+          local _item_line_length_bytes=
+          _item_line_length_bytes="${#_print_item}"
+
+          LANG="${_LANG}" LC_ALL="${_LC_ALL}"
+
+          local _item_line_length_diff=
+          _item_line_length_diff=$(((_item_line_length_bytes-_item_line_length_chars)/3))
+
+          local _item_line_length=
+          _item_line_length=$((_item_line_length_chars+_item_line_length_diff))
+
+          if ((_extra_length))
+          then
+            _item_line_length=$((_item_line_length+_extra_length))
+          fi
         fi
-      fi
 
-      local _print_item=
-      local _print_item_color=
-
-      if ((_no_id))
-      then
-        _print_item="${_list_item}"
-        _print_item_color="${_list_item}"
-      else
-        local _list_item_id="${_id_item}${_spaces}${_list_item}"
-        local _list_item_id_color="${_id_item_color}${_spaces}${_list_item}"
-
-        _print_item="${_list_item_id}"
-        _print_item_color="${_list_item_id_color}"
-      fi
-
-      if ((_list_color_enabled))  &&
-         ! ((_list_filenames))    &&
-         ! ((_no_id))
-      then
-        # Calculate apparent length of the list item string, with byte and
-        # character calculations for handling unicode characters.
-        #
-        # More info: https://stackoverflow.com/a/31009961
-        local _item_line_length_chars=
-        _item_line_length_chars="${#_print_item}"
-
-        LANG=C LC_ALL=C
-
-        local _item_line_length_bytes=
-        _item_line_length_bytes="${#_print_item}"
-
-        LANG="${_LANG}" LC_ALL="${_LC_ALL}"
-
-        local _item_line_length_diff=
-        _item_line_length_diff=$(((_item_line_length_bytes-_item_line_length_chars)/3))
-
-        local _item_line_length=
-        _item_line_length=$((_item_line_length_chars+_item_line_length_diff))
-
-        if ((_extra_length))
+        if ((_list_color_enabled))  &&
+           ! ((_print_excerpt))     &&
+           ! ((_list_filenames))    &&
+           ! ((_no_id))
         then
-          _item_line_length=$((_item_line_length+_extra_length))
+          if [[ "${_item_line_length}" -gt "${_columns}" ]] &&
+             {
+               [[ -n "${_maybe_title:-}" ]] ||
+               [[ -n "${_first_line:-}"  ]]
+             }
+          then
+            # Turn off line-wrapping
+            printf '\033[?7l'
+          fi
         fi
-      fi
 
-      if ((_list_color_enabled))  &&
-         ! ((_print_excerpt))     &&
-         ! ((_list_filenames))    &&
-         ! ((_no_id))
-      then
-        if [[ "${_item_line_length}" -gt "${_columns}" ]] &&
-           {
-             [[ -n "${_maybe_title:-}" ]] ||
-             [[ -n "${_first_line:-}"  ]]
-           }
+        if ((_list_color_enabled))
         then
-          # Turn off line-wrapping
-          printf '\033[?7l'
-        fi
-      fi
-
-      if ((_list_color_enabled))
-      then
-        printf "%s" "${_print_item_color}"
-      else
-        printf "%s" "${_print_item}"
-      fi
-
-      if ((_list_color_enabled))  &&
-         ! ((_print_excerpt))     &&
-         ! ((_list_filenames))    &&
-         ! ((_no_id))
-      then
-        if [[ "${_item_line_length}" -gt "${_columns}" ]] &&
-           {
-             [[ -n "${_maybe_title:-}" ]] ||
-             [[ -n "${_first_line:-}"  ]]
-           }
-        then
-          # Turn on line-wrapping
-          printf '\033[?7h'
-        fi
-      fi
-
-      # End of line.
-      printf "\\n"
-
-      if ((_print_excerpt)) &&
-         [[ "${_excerpt_length}" =~ ^[1-9] ]] &&
-         _file_is_text "${_NOTEBOOK_PATH}/${__basename}"
-      then # excerpt is specified with a non-zero digit, as required by `head`.
-        if [[ -z "${_item_line_length:-}"               ]] ||
-           [[ "${_item_line_length}" -gt "${_columns}"  ]]
-        then
-          _print_line "$(printf "%-${_columns}s" '.')" | tr -d '\n'
+          printf "%s" "${_print_item_color}"
         else
-          _print_line "$(printf "%-${_item_line_length}s" '.')"
+          printf "%s" "${_print_item}"
         fi
-        head -"${_excerpt_length}" "${_NOTEBOOK_PATH}/${__basename}"
+
+        if ((_list_color_enabled))  &&
+           ! ((_print_excerpt))     &&
+           ! ((_list_filenames))    &&
+           ! ((_no_id))
+        then
+          if [[ "${_item_line_length}" -gt "${_columns}" ]] &&
+             {
+               [[ -n "${_maybe_title:-}" ]] ||
+               [[ -n "${_first_line:-}"  ]]
+             }
+          then
+            # Turn on line-wrapping
+            printf '\033[?7h'
+          fi
+        fi
+
+        # End of line.
         printf "\\n"
+
+        if ((_print_excerpt)) &&
+           [[ "${_excerpt_length}" =~ ^[1-9] ]] &&
+           _file_is_text "${_NOTEBOOK_PATH}/${__basename}"
+        then # excerpt is specified with a non-zero digit, as required by `head`.
+          if [[ -z "${_item_line_length:-}"               ]] ||
+             [[ "${_item_line_length}" -gt "${_columns}"  ]]
+          then
+            _print_line "$(printf "%-${_columns}s" '.')" | tr -d '\n'
+          else
+            _print_line "$(printf "%-${_item_line_length}s" '.')"
+          fi
+          head -"${_excerpt_length}" "${_NOTEBOOK_PATH}/${__basename}"
+          printf "\\n"
+        fi
+
+        _counter=$((_counter+1))
+      done
+
+      if ! ((_counter)) && [[ -n "${_selection:-}" ]]
+      then
+        _return_1 printf "Note not found: %s\\n" "$(_highlight "${_selection}")"
+      fi
+    fi
+  } | if ((_use_pager)) && [[ -n "${PAGER:-}" ]] && [[ ! "${PAGER}" =~ less ]]
+      then
+        "${PAGER}"
+      elif ((_use_pager)) && _command_exists "less"
+      then
+        less -r --CLEAR-SCREEN --prompt="$(_less_prompt)"
+      else
+        cat
       fi
 
-      _counter=$((_counter+1))
-    done
-
-    if ! ((_counter)) && [[ -n "${_selection:-}" ]]
-    then
-      _return_1 printf "Note not found: %s\\n" "$(_highlight "${_selection}")"
-    fi
-  fi
 }
 
 # ls ####################################################################### ls
