Add experimental MathJax support with `$NB_MATHJAX_ENABLED`.
refs gh-124

diff --git a/nb b/nb
--- a/nb
+++ b/nb
@@ -11397,6 +11397,11 @@ HEREDOC
         _pandoc_arguments+=("--from=markdown+raw_html")
       fi
 
+      if ((${NB_MATHJAX_ENABLED:-0}))
+      then
+        _pandoc_arguments+=("--mathjax=/--mathjax/tex-chtml.js")
+      fi
+
       {
         if _piped_input
         then
@@ -11569,6 +11574,18 @@ HEREDOC
     }
   }());
 </script>
+HEREDOC
+      fi
+
+      if ((${NB_MATHJAX_ENABLED:-0}))
+      then
+        if [[ ! -e "${NB_DIR}/.assets/MathJax" ]] && ! ((${NB_TESTING:-0}))
+        then
+          _env install --mathjax
+        fi
+
+        cat <<HEREDOC
+<script id="MathJax-script" async src="/--mathjax/tex-chtml.js"></script>
 HEREDOC
       fi
 
@@ -14670,7 +14687,7 @@ _env() {
 
   case "${_subcommand}" in
     install)
-      if [[ ! "${2:-}" == "--ace"     ]]
+      if ! _contains "${2:-}" "--ace" "--mathjax"
       then # skip to next section if `_env install --ace`
         # packages: curl pandoc pygments w3m ripgrep tig
         if [[ -x "$(command -v apk)"  ]]
@@ -14766,6 +14783,21 @@ _env() {
           _exit_1 printf "Unable to \`cd\` to %s\\n" "${NB_DIR}/.assets"
 
         git clone https://github.com/ajaxorg/ace-builds.git
+      fi
+
+      # install MathJax editor
+
+      if ((${NB_MATHJAX_ENABLED:-0})) && [[ ! -e "${NB_DIR}/.assets/MathJax" ]]
+      then
+        if [[ ! -e "${NB_DIR}/.assets" ]]
+        then
+          mkdir "${NB_DIR}/.assets"
+        fi
+
+        cd "${NB_DIR}/.assets" ||
+          _exit_1 printf "Unable to \`cd\` to %s\\n" "${NB_DIR}/.assets"
+
+        git clone https://github.com/mathjax/MathJax.git
       fi
 
       ;;
@@ -20828,7 +20860,7 @@ HEREDOC
 
     local _message_body=
 
-    if [[ "${_request_method}"  == "POST"     ]]  &&
+    if [[ "${_request_method}"  == "POST"         ]]  &&
        ((${_content_length:-0}))
     then
       read -r -n "${_content_length}" _message_body
@@ -20836,12 +20868,24 @@ HEREDOC
 
     # serve ace editor files
 
-    if [[ "${_request_uri}"     =~ /--ace/.*  ]]
+    if [[ "${_request_uri}"     =~ /--ace/.*      ]]
     then
       local _target_relative_path="${_request_uri#/--ace/}"
 
       _browse_respond_with 200 \
         "${NB_DIR}/.assets/ace-builds/src-min-noconflict/${_target_relative_path}"
+
+      return 0
+    fi
+
+    # serve mathjax files
+
+    if [[ "${_request_uri}"     =~ /--mathjax/.*  ]]
+    then
+      local _target_relative_path="${_request_uri#/--mathjax/}"
+
+      _browse_respond_with 200 \
+        "${NB_DIR}/.assets/MathJax/es5/${_target_relative_path}"
 
       return 0
     fi
