Develop full interface for `settings`.

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -2277,11 +2277,14 @@ Description:
   Print program environment variables.
 HEREDOC
 _env() {
+  printf "EDITOR=%s\\n" "${EDITOR}"
+  printf "NOTES_AUTO_SYNC=%s\\n" "${NOTES_AUTO_SYNC}"
   printf "NOTES_DIR=%s\\n" "${NOTES_DIR}"
   printf "NOTES_DATA_DIR=%s\\n" "${NOTES_DATA_DIR}"
-  printf "NOTES_AUTO_SYNC=%s\\n" "${NOTES_AUTO_SYNC}"
+  printf "NOTES_DEFAULT_EXTENSION=%s\\n" "${NOTES_DEFAULT_EXTENSION}"
+  printf "NOTES_ENCRYPTION_TOOL=%s\\n" "${NOTES_ENCRYPTION_TOOL}"
+  printf "NOTES_HIGHLIGHT_COLOR=%s\\n" "${NOTES_HIGHLIGHT_COLOR}"
   printf "NOTESRC_PATH=%s\\n" "${NOTESRC_PATH}"
-  printf "EDITOR=%s\\n" "${EDITOR}"
 }
 
 # export ######################################################################
@@ -2905,7 +2908,7 @@ Usage:
   ${_ME} init [<remote-url>]
 
 Description:
-  Initialize the local data directory and generate a ~/.notesrc configruation
+  Initialize the local data directory and generate a ~/.notesrc configuration
   file if it doesn't exist.
 
 Examples:
@@ -2969,7 +2972,7 @@ HEREDOC
 # Default: 1
 #
 # By default, operations that trigger a git commit like \`add\`, \`edit\`,
-# and \`delete\` will also sync notebook changes to the remote repository, if
+# and \`delete\` will sync notebook changes to the remote repository, if
 # one is set.
 #
 # To disable this behavior, uncomment the following line.
@@ -4375,48 +4378,241 @@ _q() {  _search "${@}"; }
 
 desc "settings" <<HEREDOC
 Usage:
-  ${_ME} settings [colors]
+  ${_ME} settings
+  ${_ME} settings colors
+  ${_ME} settings edit
+  ${_ME} settings get <setting>
+  ${_ME} settings set <setting> <value>
+  ${_ME} settings unset <setting>
 
 Subcommands:
-  (default)  Open the ~/.notesrc configuration file in \`\$EDITOR\`.
-  colors     Print a table of color numbers in the colors they represent.
+  (default)  Print this help information.
+  colors     Print a table of available colors and their xterm color numbers.
+  edit       Open the ~/.notesrc configuration file in \`\$EDITOR\`.
+  get        Print the current value of <setting>.
+  set        The <setting> to <value>.
+  unset      Unset <setting>, returning it to the default value.
 
 Description:
-  Configure \`notes\`.
+  Configure \`notes\`. Use \`settings set\` to customize a setting and
+  \`settings unset\` to restore the default for a setting.
 
-  For more information about .notesrc, visit:
-  https://github.com/xwmx/notes#configuration
+Settings:
+  EDITOR
+    The command line text editor to use with \`notes\`. Example Values:
+    'vim', 'emacs', 'code', 'subl', 'atom', 'macdown'
+
+  NOTES_AUTO_SYNC
+    Default: '1'
+
+    By default, operations that trigger a git commit like \`add\`, \`edit\`,
+    and \`delete\` will sync notebook changes to the remote repository, if one
+    is set. To disable this behavior, set this to '0'.
+
+  NOTES_DEFAULT_EXTENSION
+    Default: 'md'
+
+    The default extension to use for notes files. Change to 'org' for Emacs
+    Org mode files, 'rst' for reStructuredText, 'txt' for plain text, or
+    whatever you prefer.
+
+  NOTES_DIR
+    Default: '~/.notes'
+
+    The location of the directory that contains the notebooks.
+
+  NOTES_ENCRYPTION_TOOL
+    Default: 'openssl'
+
+    The tool used for encrypting notes. Supported Values: 'openssl', 'gpg'
+
+  NOTES_HIGHLIGHT_COLOR
+    Default: 11 (yellow) for 256 color terminals, 3 (yellow) for 8 color.
+
+    Set highlighting color. This should be set to an xterm color number between
+    0 and 255. To view a table of available colors and numbers, run:
+    \`notes settings colors\`.
+
+Example:
+  ${_ME} settings set NOTES_DEFAULT_EXTENSION 'org'
+  ${_ME} settings unset NOTES_HIGHLIGHT_COLOR
+  ${_ME} settings colors
 HEREDOC
 _settings() {
+  # Usage: _notes_settings_colors
+  _notes_settings_colors() {
+    _notes_settings_print_color(){
+        for __color_number
+        do
+          printf '\e[38;5;%dm %3d ' \
+            "${__color_number}" \
+            "${__color_number}"
+        done
+        # printf '\e[0m \n'
+        printf '\e[0m '
+    }
+
+    _notes_settings_print_color {0..15}
+
+    for ((_i=0;_i<6;_i++))
+    do
+      _notes_settings_print_color $(seq $((_i*36+16)) $((_i*36+51)))
+    done
+
+    _notes_settings_print_color {232..255}
+
+    printf "\\n"
+  }
+
+  # Usage: _notes_settings_get <setting>
+  _notes_settings_get() {
+    _notes_settings_validate "${1}" &&
+      _env | grep "${1}" | cut -d= -f2
+  }
+
+  # Usage: _notes_settings_set <setting> <value>
+  _notes_settings_set() {
+    local _entry
+    _entry="export ${1:-}=${2:-} # Added by \`notes\` • $(date)"
+
+    _notes_settings_validate "${1:-}" &&
+      _notes_settings_validate_value "${1:-}" "${2:-}" &&
+      _notes_settings_unset "${1}" > /dev/null 2>&1     &&
+      printf "\\n%s\\n" "${_entry}" >> "${NOTESRC_PATH}" &&
+      printf "%s set to '%s'\\n" "${1:-}" "${2:-}"
+  }
+
+  # Usage: _notes_settings_unset <setting>
+  _notes_settings_unset() {
+    _notes_settings_validate "${1}" &&
+      "${_SED_I_COMMAND[@]}" \
+        -e "s/^export ${1}.*Added by.*$//g" \
+        "${NOTESRC_PATH}" &&
+        printf "%s restored to the default: '%s'\\n" \
+          "${1:-}" \
+          "$(eval "${1:-}='' ${_MY_PATH} settings get ${1:-}")"
+  }
+
+  # Usage: _notes_settings_validate <setting>
+  _notes_settings_validate() {
+    local _match=0
+    local _available_settings=(
+      EDITOR
+      NOTES_AUTO_SYNC
+      NOTES_DEFAULT_EXTENSION
+      NOTES_DIR
+      NOTES_ENCRYPTION_TOOL
+      NOTES_HIGHLIGHT_COLOR
+    )
+    for __setting in "${_available_settings[@]}"
+    do
+      if [[ "${__setting}" == "${1:-}" ]]
+      then
+        _match=1
+      fi
+    done
+
+    if ! ((_match))
+    then
+      printf "Setting not found: '%s'\n" "${1:-}"
+      return 1
+    fi
+  }
+
+  # Usage: _notes_settings_validate_color <setting> <value>
+  _notes_settings_validate_value() {
+    if [[ "${1:-}" == 'EDITOR' ]] ||
+       [[ "${1:-}" == 'NOTES_DEFAULT_EXTENSION' ]] ||
+       [[ "${1:-}" == 'NOTES_DIR' ]]
+    then
+      if [[ -n "${2:-}" ]]
+      then
+        return 0
+      else
+        printf "%s requires a value.\\n" "${1:-}"
+        return 1
+      fi
+    elif [[ "${1:-}" == 'NOTES_AUTO_SYNC' ]]
+    then
+      if [[ "${2:-}" =~ ^0|1$ ]]
+      then
+        return 0
+      else
+        printf "NOTES_AUTO_SYNC must be either '0' or '1'.\\n"
+        return 1
+      fi
+    elif [[ "${1:-}" == 'NOTES_ENCRYPTION_TOOL' ]]
+    then
+      if [[ "${2:-}" =~ ^openssl|gpg$ ]]
+      then
+        return 0
+      else
+        printf "NOTES_ENCRYPTION_TOOL must be either 'openssl' or 'gpg'.\\n"
+        return 1
+      fi
+    elif [[ "${1:-}" == 'NOTES_HIGHLIGHT_COLOR' ]]
+    then
+      if [[ "${2:-}" =~ ^[0-9]{1,3}$ ]] &&
+         [[ "${2:-}" -lt '256' ]]
+      then
+        return 0
+      else
+        printf "NOTES_HIGHLIGHT_COLOR must be number between 0 and 255.\\n"
+        return 1
+      fi
+    else
+      return 0
+    fi
+  }
+
+  local _subcommand=
+
   while ((${#}))
   do
     local _arg="${1:-}"
-    local _val="${2:-}"
 
     case "${_arg}" in
       color|colors)
-        _notes_settings_color(){
-            for __color_number
-            do
-              printf '\e[38;5;%dm %03d ' \
-                "${__color_number}" \
-                "${__color_number}"
-            done
-            printf '\e[0m \n'
-        }
+        _notes_settings_colors
+        return 0
+        ;;
+      edit)
+        _edit_file "${NOTESRC_PATH}" --no-wait
+        return 0
+        ;;
+      get)
+        if [[ -z "${2:-}" ]]
+        then
+          _help settings
+          return 1
+        fi
 
-        IFS=$' \t\n' _notes_settings_color {0..15}
+        _notes_settings_get "${2:-}"
+        return 0
+        ;;
+      set)
+        if [[ -z "${2:-}" ]] || [[ -z "${3:-}" ]]
+        then
+            _help settings
+            return 1
+        fi
 
-        for ((_i=0;_i<6;_i++))
-        do
-          IFS=$' \t\n' \
-            _notes_settings_color $(seq $((_i*36+16)) $((_i*36+51)))
-        done
+        _notes_settings_set "${2:-}" "${3:-}"
+        return 0
+        ;;
+      unset)
+        if [[ -z "${2:-}" ]]
+        then
+          _help settings
+          return 1
+        fi
 
-        IFS=$' \t\n' _notes_settings_color {232..255}
+        _notes_settings_unset "${2:-}"
+        return 0
         ;;
       *)
-        _edit_file "${HOME}/.notesrc" --no-wait
+        _help settings
+        return 0
         ;;
     esac
 
