Add `_repo_add()` and `_repo_list()` nested functions.
The code for `_repo()` has been getting long, so move into nested
functions to improve organization.

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -1239,60 +1239,77 @@ Usage:
 HEREDOC
 # TODO: Add description.
 _repo() {
+  # _repo_add()
+  #
+  # Usage:
+  #   _repo_add <name> [<remote_url>]
+  _repo_add() {
+    local _name="${1:-}"
+    if [[ -z "${_name}" ]]
+    then
+      _die "${_ME}" help repo
+    fi
+
+    if [[ -e "${NOTES_DIR}/${_name}" ]]
+    then
+      _die printf "Already exists: ${_name}"
+    fi
+
+    local _repo_url="${2:-}"
+    if [[ -n "${_repo_url}" ]]
+    then
+      git clone "${_repo_url}" "${NOTES_DIR}/${_name}"
+      printf "%s\n" "${_name}" > "${NOTES_DIR}/.current"
+    else
+      mkdir -p "${NOTES_DIR}/${_name}"
+      cd "${NOTES_DIR}/${_name}" && git init
+    fi
+    printf "Added: %s\n" "${_name}"
+  }
+  # _repo_list()
+  #
+  # Usage:
+  #   _repo_list
+  _repo_list() {
+    local _files=($(ls -1 "${NOTES_DIR}"))
+    for _item in "${_files[@]}"
+    do
+      if [[ -e "${NOTES_DIR}/${_item}/.git" ]]
+      then # it's a git repository.
+        local _current="$(cat "${NOTES_DIR}/.current")"
+        local _formatted_name
+        local _origin_url
+
+        if [[ -n "${_current}" ]] &&
+           [[ "${_current}" == "${_item}" ]]
+        then # it's the current repository.
+          _formatted_name="$(_highlight "${_item}")"
+        else
+          _formatted_name="${_item}"
+        fi
+
+        cd "${NOTES_DIR}/${_item}" || _die printf "_repo() \`cd\` failed."
+        _origin_url="$(git config --get remote.origin.url || echo '')"
+
+        if [[ -n "${_origin_url}" ]]
+        then
+          printf "%s\n" "${_formatted_name}	(${_origin_url})"
+        else
+          printf "%s\n" "${_formatted_name}"
+        fi
+      fi
+    done
+  }
+
   local _subcommand="${1:-}"
   local _name="${2:-}"
+
   case "${_subcommand}" in
     add)
-      if [[ -z "${_name}" ]]
-      then
-        _die "${_ME}" help repo
-      fi
-
-      if [[ -e "${NOTES_DIR}/${_name}" ]]
-      then
-        _die printf "Already exists: ${_name}"
-      fi
-
-      local _repo_url="${3:-}"
-      if [[ -n "${_repo_url}" ]]
-      then
-        git clone "${_repo_url}" "${NOTES_DIR}/${_name}"
-        printf "%s\n" "${_name}" > "${NOTES_DIR}/.current"
-      else
-        mkdir -p "${NOTES_DIR}/${_name}"
-        cd "${NOTES_DIR}/${_name}" && git init
-      fi
-      printf "Added: %s\n" "${_name}"
+      _repo_add "${_name:-}" "${3:-}"
       ;;
     list)
-      local _files=($(ls -1 "${NOTES_DIR}"))
-      for _item in "${_files[@]}"
-      do
-        if [[ -e "${NOTES_DIR}/${_item}/.git" ]]
-        then # it's a git repository.
-          local _current="$(cat "${NOTES_DIR}/.current")"
-          local _formatted_name
-          local _origin_url
-
-          if [[ -n "${_current}" ]] &&
-             [[ "${_current}" == "${_item}" ]]
-          then # it's the current repository.
-            _formatted_name="$(_highlight "${_item}")"
-          else
-            _formatted_name="${_item}"
-          fi
-
-          cd "${NOTES_DIR}/${_item}" || _die printf "_repo() \`cd\` failed."
-          _origin_url="$(git config --get remote.origin.url || echo '')"
-
-          if [[ -n "${_origin_url}" ]]
-          then
-            printf "%s\n" "${_formatted_name}	(${_origin_url})"
-          else
-            printf "%s\n" "${_formatted_name}"
-          fi
-        fi
-      done
+      _repo_list
       ;;
     use)
       if [[ -z "${_name}" ]]
