Add `search --all` option.
When the `--all` option is used, all notebooks are searched.

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -184,13 +184,13 @@ _command_exists() {
 #   0  <item> is found in <list>.
 #   1  <item> is not found in <list>.
 _get_index() {
-  _debug printf "_get_index() \${1}: '%s'\n" "${1:-}"
-  _debug printf "_get_index() \${@:2}: '%s'\n" "${@:2}"
+  # _debug printf "_get_index() \${1}: '%s'\n" "${1:-}"
+  # _debug printf "_get_index() \${@:2}: '%s'\n" "${@:2}"
 
   local _filename="${1:-}"
   local -a _files=(${@:2})
 
-  _debug printf "_get_index() \${_files[@]}: '%s'\n" "${_files[@]}"
+  # _debug printf "_get_index() \${_files[@]}: '%s'\n" "${_files[@]}"
 
   if [[ -z "${_filename}" ]] || [[ -z "${_files[*]}" ]]
   then
@@ -199,7 +199,7 @@ _get_index() {
 
   for _i in "${!_files[@]}"
   do
-    _debug printf "_get_index() \${_files[$_i]} : '%s'\n" "${_files[$_i]}"
+    # _debug printf "_get_index() \${_files[$_i]} : '%s'\n" "${_files[$_i]}"
     if [[ "${_files[$_i]}" == "${_filename}" ]]
     then
       printf "%s\n" "${_i}"
@@ -884,7 +884,7 @@ Usage:
   $_ME notebook list [<name>] [--names]
   $_ME notebook rename <old-name> <new-name>
   $_ME notebook use <name>
-  $_ME search <query> [--path]
+  $_ME search <query> [--all] [--path]
   $_ME show (<index> | <filename> | <path> | <title>)
   $_ME show <selection> ([--index] | [--path] | [---render]) [--dump [--raw]]
   $_ME sync
@@ -1416,9 +1416,10 @@ _books()  { _notebooks "${@}"; }
 
 desc "search" <<HEREDOC
 Usage:
-  $_ME search <query> [--path]
+  $_ME search <query> [--all] [--path]
 
 Options:
+  --all   Search all notebooks.
   --path  Print the full path for each file with query matches.
 
 Description:
@@ -1427,6 +1428,7 @@ Description:
   1. http://beyondgrep.com/
 HEREDOC
 _search() {
+  local _all=0
   local _arguments=("${@:1}")
   local _query=
   local _print_paths=0
@@ -1435,6 +1437,9 @@ _search() {
   for _arg in "${_arguments[@]:-}"
   do
     case "${_arg}" in
+      --all)
+        _all=1
+        ;;
       --path)
         _print_paths=1
         ;;
@@ -1452,60 +1457,105 @@ _search() {
     $_ME help "search"
     return 1
   else
-    local _files=
-    _files=($(_list --noindex))
+    local _target_notebooks=()
 
-    if _command_exists "ack"
-    then # ack is available.
-      ack "${_query}" "${NOTES_DATA_DIR}" \
-        --ignore-case \
-        --noheading \
-        --color-lineno='bold green' \
-        --color-match='black on_blue'
-    else # fall back to POSIX grep.
-      # Add /dev/null so file path is printed even if there is only one
-      # matching file. Reference: http://stackoverflow.com/a/15432718
-      grep --ignore-case -n "${_query}" "${NOTES_DATA_DIR}"/* /dev/null
-    fi | while read -r _line
+    if ((_all))
+    then
+      _target_notebooks=($($_ME notebooks --names))
+    else
+      _target_notebooks=($(_notebook))
+    fi
+
+    _debug printf \
+      "_search() \$_target_notebooks: '%s'\n" \
+      "${_target_notebooks[*]}"
+
+    for _scope in "${_target_notebooks[@]:-}"
     do
-      local _path=
-      local _filename=
-      local _index=
-      local _indexed_filename=
-      local _hit=
+      local _files=
+      _files=($($_ME "${_scope}:list" --noindex || printf ''))
 
-      # Use `sed` to remove color from output.
-      # http://unix.stackexchange.com/a/140255
-      _path="$(
-        printf "%s\n" "${_line}" \
-          | cut -d: -f 1 \
-          | sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g"
-      )"
+      _debug printf "_search() \$_scope: '%s'\n" "${_scope}"
+      # _debug printf "_search() \$_files: '%s'\n" "${_files[*]}"
 
-      if ((_print_paths))
-      then
-        if [[ "${_last_path}" != "${_path}" ]]
-        then # match is in a different file than the last match
-          printf "%s\n" "${_path}"
+      if _command_exists "ack"
+      then # ack is available.
+        ack "${_query}" "${NOTES_DIR}/${_scope}" \
+          --ignore-case \
+          --noheading \
+          --color-lineno='bold green' \
+          --color-match='black on_blue' \
+            || return 0 # Don't fail out within a single scope.
+      else # fall back to POSIX grep.
+        # Add /dev/null so file path is printed even if there is only one
+        # matching file. Reference: http://stackoverflow.com/a/15432718
+        grep \
+          --ignore-case \
+          -n "${_query}" "${NOTES_DIR}/${_scope}"/* /dev/null \
+            || return 0 # Don't fail out within a single scope.
+      fi | while read -r _line
+      do
+        local _path=
+        local _filename=
+        local _index=
+        # Define `_indexed_filename` with and without color to have a version
+        # without the additional length from `tput` calls.
+        local _indexed_filename=
+        local _indexed_filename_color=
+        local _hit=
+
+        # Use `sed` to remove color from output.
+        # http://unix.stackexchange.com/a/140255
+        _path="$(
+          printf "%s\n" "${_line}" \
+            | cut -d: -f 1 \
+            | sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g"
+        )"
+
+        if ((_print_paths))
+        then
+          if [[ "${_last_path}" != "${_path}" ]]
+          then # match is in a different file than the last match
+            printf "%s\n" "${_path}"
+          fi
+        else
+          _filename="$(basename "${_path}")"
+          _index="$(_get_index "${_filename}" "${_files[@]}")"
+
+          if ((_all))
+          then
+            _indexed_filename_color="[$(_highlight "${_scope}:${_index}")] ${_filename}"
+            _indexed_filename="[${_scope}:${_index}] ${_filename}"
+          else
+            _indexed_filename_color="[$(_highlight "${_index}")] ${_filename}"
+            _indexed_filename="[${_index}] ${_filename}"
+          fi
+
+          # printf "_search() \$_index: '%s'\n" "${_index}"
+          # printf "_search() \$_last_path: '%s'\n" "${_last_path}"
+          # printf "_search() \$_path: '%s'\n" "${_path}"
+
+          if [[ "${_last_path}" != "${_path}" ]]
+          then # match is in a different file than the last match
+            printf "%s\n" "${_indexed_filename_color}"
+            _print_line "${_indexed_filename}"
+          fi
+
+          _hit="$(printf "%s\n" "${_line}" | cut -d: -f 2-)"
+          printf "%s\n\n" "${_hit}"
         fi
-      else
-        _filename="$(basename "${_path}")"
-        _index="$(_get_index "${_filename}" "${_files[@]}")"
-        _indexed_filename="[$(_highlight "${_index}")] ${_filename}"
 
-        if [[ "${_last_path}" != "${_path}" ]]
-        then # match is in a different file than the last match
-          printf "%s\n" "${_indexed_filename}"
-          # Use `[${_i}]` to avoid additional length from `tput` calls.
-          _print_line "[${_index}] ${_filename}"
-        fi
-
-        _hit="$(printf "%s\n" "${_line}" | cut -d: -f 2-)"
-        printf "%s\n\n" "${_hit}"
-      fi
-
-      _last_path="${_path}"
-    done
+        _last_path="${_path}"
+      done
+    done | if read -r _line
+    then # output is present
+      # Print the test line then `cat` the rest.
+      printf "%s\n" "${_line}"
+      cat
+      return 0
+    else
+      return 1
+    fi
   fi
 }
 
