Use consistent 'Note not found' messages

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -1730,7 +1730,7 @@ _bookmark() {
     _basename="$(_get_selection_basename "${_selection}")"
     if [[ -z "${_basename}" ]]
     then
-      printf "Note not found.\n"
+      printf "Note not found: '%s'.\\n" "${_selection}"
       return 1
     fi
     _set_selection_notebook "${_selection}"
@@ -1999,7 +1999,7 @@ _delete() {
   _debug printf "_delete() \${_basename}: '%s'\\n" "${_basename}"
   if [[ -z "${_basename}" ]]
   then
-    printf "Note not found.\n"
+    printf "Note not found: '%s'.\\n" "${_selection}"
     return 1
   fi
 
@@ -2133,7 +2133,7 @@ _edit() {
   _debug printf "_edit() \${_basename}: '%s'\\n" "${_basename}"
   if [[ -z "${_basename}" ]]
   then
-    printf "Note not found.\n"
+    printf "Note not found: '%s'.\\n" "${_selection}"
     return 1
   fi
 
@@ -2322,7 +2322,7 @@ _export() {
 
   if [[ -z "${_basename:-}" ]] || [[ ! -e "${NOTES_DATA_DIR}/${_basename:-}" ]]
   then
-    printf "Note not found: %s\n" "${_selection}"
+    printf "Note not found: '%s'.\\n" "${_selection}"
     return 1
   fi
   _debug printf "_export() \${_basename}: %s\\n" "${_basename}"
@@ -3233,9 +3233,9 @@ HEREDOC
       _counter=$((_counter+1))
     done
 
-    if ! ((_counter))
+    if ! ((_counter)) && [[ -n "${_selection:-}" ]]
     then
-      printf "Note not found: %s\\n" "${_selection}"
+      printf "Note not found: '%s'.\\n" "${_selection}"
       printf "Help & Usage Info:\n"
       printf "  notes help\\n"
       return 1
@@ -4430,7 +4430,7 @@ _show() {
   _debug printf "_show() \${_basename}: '%s'\\n" "${_basename}"
   if [[ -z "${_basename}" ]]
   then
-    printf "Note not found.\n"
+    printf "Note not found: '%s'.\\n" "${_selection}"
     return 1
   fi
   _set_selection_notebook "${_selection}"
