Expand experimental export/import.

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -429,6 +429,29 @@ _get_title() {
   fi
 }
 
+# _get_unique_basename()
+#
+# Usage:
+#   _get_unique_basename <file extension>
+#
+# Description:
+#   Get a unique basename that doesn't conflict with any existing file.
+_get_unique_basename() {
+  local _filename
+  _filename="$(date -u "+%Y%m%d%H%M%S")"
+  local _file_type="${1:-md}"
+
+  local _uniqueness_counter=0
+  local _unique_filename="${_filename}"
+  while [[ -e "${NOTES_DATA_DIR}/${_unique_filename}.${_file_type}" ]]
+  do
+    printf -v _unique_filename -- "%s-%02d" \
+      "${_filename}" \
+      "$(( ++_uniqueness_counter ))"
+  done
+  printf "%s\n" "${_unique_filename}.${_file_type}"
+}
+
 # _git_checkpoint()
 #
 # Usage:
@@ -958,7 +981,7 @@ _add() {
   done
 
   local _basename
-  _basename="${_unique_filename}.${_file_type}"
+  _basename="$(_get_unique_basename "${_file_type}")"
 
   _file_path="${NOTES_DATA_DIR}/${_basename}"
 
@@ -1206,50 +1229,60 @@ _env() {
 
 desc "export" <<HEREDOC
 Usage:
-  ${_ME} export (<id> | <filename> | <path> | <title>) <path>
-                [--convert [<pandoc options>...]]
+  ${_ME} export (<id> | <filename> | <path> | <title>) <path> [--force]
+                [<pandoc options>...]
+  ${_ME} export convert (<id> | <filename> | <path> | <title>)
+                [<pandoc options>...]
 
 Options:
-  --convert   Use \`pandoc\` to convert the note from its current format
-              to the format of the output file indicated by the file extension
-              in \`<path>\`. Any additional arguments are passed directly
-              to \`pandoc\`. See the \`pandoc\` help information for available
-              options.
+  --force    Skip the confirmation prompt when overwriting an existing file.
 
-
-  1. http://pandoc.org/
+Subcommands:
+  (default)  Export a file to <path>. Convert the note using \`pandoc\` to
+             the file extension in <path>.
+  convert    Export the file to standard output or a file using \`pandoc\`.
 
 Description:
-  Export a file.
+  Export a file from the notebook.
+
+  If Pandoc [1] is available, convert the note from its current format
+  to the format of the output file as indicated by the file extension
+  in <path>. Any additional arguments are passed directly to Pandoc.
+  See the Pandoc help information for available options.
+
+  1. http://pandoc.org/
 
 Examples:
   # Export an Emacs Org mode note
   ${_ME} export example.org /path/to/example.org
 
-  # Export a Markdown note and convert to standalone HTML
-  ${_ME} export example.md /path/to/example.html --convert --standalone
+  # Export a Markdown note to HTML and print to standard output
+  ${_ME} export example.md --from=markdown_strict
 
-  # Export a Markdown note and convert to Microsoft Office .docx
-  ${_ME} export example.md /path/to/example.docx --convert --standalone
-
+  # Export a Markdown note to a .docx Microsoft Office Word document
+  ${_ME} export example.md /path/to/example.docx
 HEREDOC
 _export() {
   local _args=()
   local _convert=0
+  local _force=0
   local _selection=
   local _target_path=
 
   for __arg in "${@:-}"
   do
     case "${__arg}" in
-      --convert)
+      convert)
         _convert=1
+        ;;
+      --force)
+        _force=1
         ;;
       *)
         if [[ -z "${_selection:-}" ]]
         then
           _selection="${__arg}"
-        elif [[ -z "${_target_path:-}" ]]
+        elif ! ((_convert)) && [[ -z "${_target_path:-}" ]]
         then
           _target_path="${__arg}"
         else
@@ -1259,7 +1292,7 @@ _export() {
     esac
   done
 
-  if [[ -z "${_selection:-}" ]] || [[ -z "${_target_path:-}" ]]
+  if [[ -z "${_selection:-}" ]]
   then
     ${_ME} help "export"
     return 1
@@ -1268,44 +1301,63 @@ _export() {
 
   local _basename
   _basename="$(_get_selection_basename "${_selection}")"
-
-  if [[ ! -e "${NOTES_DATA_DIR}/${_basename}" ]]
+  if [[ -z "${_basename:-}" ]] || [[ ! -e "${NOTES_DATA_DIR}/${_basename:-}" ]]
   then
     printf "Note not found: %s\n" "${_selection}"
     return 1
   fi
-
-  if [[ -e "${target_path:-}" ]]
-  then
-    if ! ((_force))
-    then
-      printf "File exists at '%s'\\n"  \
-        "${target_path}"
-      while true
-      do
-        read -r -p "Overwrite existing file? [y/N] " __yn
-        case ${__yn} in
-          [Yy]*)
-            break
-            ;;
-          *)
-            printf "Exiting...\\n"
-            exit 0
-            ;;
-        esac
-      done
-    fi
-  fi
-
+  _debug printf "_export() \${_basename}: %s\\n" "${_basename}"
 
   if ((_convert))
   then
-    pandoc \
-      -o "${_target_path}" \
-      --standalone \
-      "${NOTES_DATA_DIR}/${_basename}"
+    if _command_exists 'pandoc'
+    then
+      pandoc "${NOTES_DATA_DIR}/${_basename}" "${_args[@]:-}"
+    else
+      printf "Pandoc required. http://pandoc.org/\n"
+      return 1
+    fi
   else
-    cp "${NOTES_DATA_DIR}/${_basename}" "${_target_path}"
+    if [[ -z "${_target_path:-}" ]]
+    then
+      ${_ME} help "export"
+      return 1
+    fi
+    _debug printf "_export() \${target_path}: %s\\n" "${_target_path}"
+
+    if [[ -e "${_target_path:-}" ]]
+    then
+      if ! ((_force))
+      then
+        printf "File exists at '%s'\\n"  \
+          "${_target_path}"
+        while true
+        do
+          read -r -p "Overwrite existing file? [y/N] " __yn
+          case ${__yn} in
+            [Yy]*)
+              break
+              ;;
+            *)
+              printf "Exiting...\\n"
+              exit 0
+              ;;
+          esac
+        done
+      fi
+    fi
+
+    if _command_exists 'pandoc'
+    then
+      pandoc \
+        -o "${_target_path}" \
+        ${_args[@]:-} \
+        --standalone \
+        "${NOTES_DATA_DIR}/${_basename}"
+    else
+      cp "${NOTES_DATA_DIR}/${_basename}" "${_target_path}"
+    fi &&
+      printf "Exported '%s' to '%s'\n" "${_selection}" "${_target_path}"
   fi
 }
 
@@ -1424,11 +1476,18 @@ _history() {
 
 desc "import" <<HEREDOC
 Usage:
-  ${_ME} import copy <path>
-  ${_ME} import download <url>
-  ${_ME} import move <path>
+  ${_ME} import (<path> | <url>)  [--add | --overwrite]
+  ${_ME} import copy <path>       [--add | --overwrite]
+  ${_ME} import download <url>    [--add | --overwrite] [--convert]
+  ${_ME} import move <path>       [--add | --overwrite]
+
+Options:
+  --add        Add a new note with the imported content.
+  --convert    Convert HTML content to Markdown.
+  --overwrite  Overwrite existing note with the same file name if one exists.
 
 Subcommands:
+  (default) Copy or download the file in <path> or <url>.
   copy      Copy the file at <path> into the current notebook.
   download  Download the file at <url> into the current notebook.
   move      Copy the file at <path> into the current notebook.
@@ -1437,8 +1496,175 @@ Description:
   Copy, move, or download a file into the current notebook.
 HEREDOC
 _import() {
-  # TODO
-  :
+  _import_validate_path() {
+    if [[ -z "${1:-}" ]]
+    then
+      "${_ME}" help import
+      return 1
+    elif [[ ! -e "${1:-}" ]]
+    then
+      printf "File not found: %s\n" "${1:-}"
+      return 1
+    fi
+  }
+
+  _import_validate_target() {
+    local _target_path="${1:-}"
+    if [[ -e "${_target_path}" ]]
+    then
+      if ! ((_overwrite))
+      then
+        printf "File exists at '%s'\\n"  \
+          "${_target_path}"
+        while true
+        do
+          read -r -p "Overwrite existing file? [y/N] " __yn
+          case ${__yn} in
+            [Yy]*)
+              break
+              ;;
+            *)
+              printf "Exiting...\\n"
+              exit 0
+              ;;
+          esac
+        done
+      fi
+    fi
+  }
+
+
+  local _add=0
+  local _basename=
+  local _convert=0
+  local _overwrite=0
+  local _path=
+  local _subcommand=
+  local _url=
+
+  for __arg in "${@:-}"
+  do
+    case "${__arg}" in
+      copy|download|move)
+        _subcommand="${__arg}"
+        ;;
+      --add)
+        _add=1
+        ;;
+      --convert)
+        _convert=1
+        ;;
+      --overwrite)
+        _overwrite=1
+        ;;
+      *)
+        if [[ -n "${_subcommand:-}" ]]
+        then
+          if [[ "${_subcommand}" == "download" ]]
+          then
+            _url="${__arg:-}"
+          else
+            _path="${__arg:-}"
+          fi
+        else
+          if [[ "${__arg:-}" =~ ^http ]]
+          then
+            _subcommand="download"
+            _url="${__arg:-}"
+          else
+            _subcommand="copy"
+            _path="${__arg:-}"
+          fi
+        fi
+        ;;
+    esac
+  done
+
+  case "${_subcommand}" in
+    copy)
+      _import_validate_path "${_path:-}"
+
+      if ((_add))
+      then
+        _basename="$(_get_unique_basename "${_file_type}")"
+      else
+        _basename="$(basename -- "${_path}")"
+      fi
+      _import_validate_target "${NOTES_DATA_DIR}/${_basename}"
+
+      cp "${_path}" "${NOTES_DATA_DIR}/${_basename}" &&
+        _index add "${_basename}" &&
+        _git_checkpoint "[NOTES] Import: ${_basename}"
+      printf "Imported '%s' to '%s'\n" "${_path}" "${_basename}"
+      ;;
+    download)
+      if ((_add))
+      then
+        curl -s "${_url}" | "${_ME}" add
+      else
+        _basename="$(basename -- "${_url}")"
+        _import_validate_target "${NOTES_DATA_DIR}/${_basename}"
+
+        if ((_convert))
+        then
+          curl "${_url}" | pandoc \
+            --from html --to markdown \
+            -o "${NOTES_DATA_DIR}/${_basename}"
+        else
+          curl "${_url}" -o "${NOTES_DATA_DIR}/${_basename}"
+        fi &&
+          _index add "${_basename}" &&
+          _git_checkpoint "\
+[NOTES] Import: ${_basename}
+
+Source:
+${_url}
+"
+        printf "Imported '%s' to '%s'\n" "${_url}" "${_basename}"
+      fi
+      ;;
+    move)
+      _import_validate_path "${_path:-}"
+      _basename="$(basename -- "${_path}")"
+
+      if ((_add))
+      then
+        cat "${_path}" | "${_ME}" add
+
+        while true
+        do
+          read -r -p "Delete the original file? [y/N] " __yn
+          case ${__yn} in
+            [Yy]*)
+              break
+              ;;
+            *)
+              printf "Exiting...\\n"
+              exit 0
+              ;;
+          esac
+        done
+
+        if hash "trash" 2>/dev/null
+        then
+          trash "${_path}"
+        else
+          rm "${_path}"
+        fi
+      else
+        _import_validate_target "${NOTES_DATA_DIR}/${_basename}"
+
+        mv "${_path}" "${NOTES_DATA_DIR}/${_basename}" &&
+          _index add "${_basename}" &&
+          _git_checkpoint "[NOTES] Import: ${_basename}"
+        printf "Imported '%s' to '%s'\n" "${_path}" "${_basename}"
+      fi
+      ;;
+    *)
+      "${_ME}" help import
+      return 1
+      ;;
+  esac
 }
 
 # index #######################################################################
